apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: gitops-addon-config
  namespace: multicluster-engine
spec:
  customizedVariables:
    - name: argoNamespace
      value: openshift-gitops
